### ISSUE TITLE
Module does not compile with Php 8.3

### ISSUE THREAD

**Issue by grosjo** [websupport-sk/pecl-memcache#115]
```
/files/src/pecl8/pecl-memcache/php7/memcache.c:42:9: error: implicit declaration of function 'ZEND_ARG_PASS_INFO'; did you mean 'ZEND_ARG_OBJ_INFO'? [-Wimplicit-function-declaration]
   42 |         ZEND_ARG_PASS_INFO(0)
      |         ^~~~~~~~~~~~~~~~~~
      |         ZEND_ARG_OBJ_INFO
/files/src/pecl8/pecl-memcache/php7/memcache.c:42:9: error: initialization of 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
/files/src/pecl8/pecl-memcache/php7/memcache.c:42:9: note: (near initialization for 'arginfo_memcache_get[1].name')
/files/src/pecl8/pecl-memcache/php7/memcache.c:42:9: error: initializer element is not constant
/files/src/pecl8/pecl-memcache/php7/memcache.c:42:9: note: (near initialization for 'arginfo_memcache_get[1].name')
/files/src/pecl8/pecl-memcache/php7/memcache.c:43:9: error: expected '}' before 'ZEND_ARG_PASS_INFO'
   43 |         ZEND_ARG_PASS_INFO(0)
      |         ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/php/main/php.h:35,
                 from /files/src/pecl8/pecl-memcache/php7/memcache.c:26:
/usr/include/php/Zend/zend_API.h:211:54: note: to match this '{'
  211 |         static const zend_internal_arg_info name[] = { \
      |                                                      ^
/usr/include/php/Zend/zend_API.h:214:9: note: in expansion of macro 'ZEND_BEGIN_ARG_INFO_EX'
  214 |         ZEND_BEGIN_ARG_INFO_EX(name, {}, ZEND_RETURN_VALUE, -1)
      |         ^~~~~~~~~~~~~~~~~~~~~~
/files/src/pecl8/pecl-memcache/php7/memcache.c:41:1: note: in expansion of macro 'ZEND_BEGIN_ARG_INFO'
   41 | ZEND_BEGIN_ARG_INFO(arginfo_memcache_get, 1)
      | ^~~~~~~~~~~~~~~~~~~
/files/src/pecl8/pecl-memcache/php7/memcache.c:49:9: error: initialization of 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   49 |         ZEND_ARG_PASS_INFO(0)
      |         ^~~~~~~~~~~~~~~~~~
/files/src/pecl8/pecl-memcache/php7/memcache.c:49:9: note: (near initialization for 'arginfo_memcache_object_get[1].name')
/files/src/pecl8/pecl-memcache/php7/memcache.c:49:9: error: initializer element is not constant
/files/src/pecl8/pecl-memcache/php7/memcache.c:49:9: note: (near initialization for 'arginfo_memcache_object_get[1].name')
/files/src/pecl8/pecl-memcache/php7/memcache.c:50:9: error: expected '}' before 'ZEND_ARG_PASS_INFO'
   50 |         ZEND_ARG_PASS_INFO(1)
      |         ^~~~~~~~~~~~~~~~~~
/usr/include/php/Zend/zend_API.h:211:54: note: to match this '{'
  211 |         static const zend_internal_arg_info name[] = { \
      |                                                      ^
/usr/include/php/Zend/zend_API.h:214:9: note: in expansion of macro 'ZEND_BEGIN_ARG_INFO_EX'
  214 |         ZEND_BEGIN_ARG_INFO_EX(name, {}, ZEND_RETURN_VALUE, -1)
      |         ^~~~~~~~~~~~~~~~~~~~~~
/files/src/pecl8/pecl-memcache/php7/memcache.c:48:1: note: in expansion of macro 'ZEND_BEGIN_ARG_INFO'
   48 | ZEND_BEGIN_ARG_INFO(arginfo_memcache_object_get, 1)

```
